services:
  backend-api:
    build: .
    command: npm run api
    environment:
      - NODE_ENV=development
      - "DATABASE_URL=${DATABASE_URL}"
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    depends_on:
      - svelte-sample
    working_dir: /root/svelte-sample
  svelte-sample:
    build: .
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - "DATABASE_URL=${DATABASE_URL}"
    ports:
      - "${SVELTE_PORT}:${SVELTE_PORT}"
    working_dir: /root/svelte-sample
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=pass1234
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
